server:
  port: 8080

spring:
  application:
    name: nacos-client-a
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: 84491d48-e4d1-4653-8c3d-652db2bdca98
        group: A_GROUP
